name: Python CI

#triger
on:
    push:
        branches:
            -main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step check th repo
            - name: Check out code
              uses: actions/checkout@v2

            # step2 set up python enviroment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            # setp3 install
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # step4 run tests
            - name: Run tests
              run: pytest
